name: SurvivalUHC
version: 1.0.0
author: Stefan Cooper
main: com.stefancooper.SurvivalUHC.Plugin
api-version: 1.21
website: https://stefancooper.com
commands:
  uhc:
    description: Configure and run a UHC
    permission: op
    usage: >
      UHC Plugin Commands
      
      Set config value:
      
      /uhc set revive.hp=4
      
      Set multiple config values:
      
      /uhc set revive.hp=4 revive.enabled=true
      
      View full config:
      
      /uhc view config
      
      View a specific config value:

      /uhc view revive.hp
      
      Unset config value:

      /uhc unset revive.hp
      
      Unset multiple config values:

      /uhc unset revive.hp revive.enabled
      
      Manually enable/disable pvp:
      
      /uhc pvp true
